---
dist: bionic
language: python
services:
- docker
install:
- mkdir -p $HOME/.local/bin
- export PATH="$HOME/.local/bin:$PATH"
- pip3 install docker==4.2.2 molecule ansible-lint yamllint flake8 openshift jmespath
- ansible-galaxy collection install -r requirements.yml
- curl -Lo $HOME/.local/bin/kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
- chmod +x $HOME/.local/bin/kind
- curl -Lo $HOME/helm.tgz https://get.helm.sh/helm-v3.3.0-linux-amd64.tar.gz
- tar xvzf $HOME/helm.tgz -C $HOME/.local/bin --strip-components 1 linux-amd64/helm
- helm repo add stable https://kubernetes-charts.storage.googleapis.com/
sudo: true
before_script:
- sudo sysctl -w vm.max_map_count=262144
script:
- OPERATORDIR="$(pwd)"
- make kustomize
- '[ -f ./bin/kustomize ] && KUSTOMIZE="$(realpath ./bin/kustomize)" || KUSTOMIZE="$(which kustomize)"'
- KUSTOMIZE_PATH=${KUSTOMIZE} TEST_OPERATOR_NAMESPACE=default molecule test -s kind-cluster
- KUSTOMIZE_PATH=${KUSTOMIZE} TEST_OPERATOR_NAMESPACE=default molecule test -s kind-namespace
deploy:
  provider: script
  script: hack/operate.sh --push-images --verbose
  on:
    branch: master
