apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sonarqubes.gpte.redhat.com
spec:
  group: gpte.redhat.com
  names:
    kind: Sonarqube
    listKind: SonarqubeList
    plural: sonarqubes
    singular: sonarqube
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
